# Site settings
name: DA_QI | 大祁
title: CHEN | 大祁和他的朋友们
email: chen807049335@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  吃啥啥不够，干啥啥不行。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dqyxw.github.io/" # the base hostname & protocol for your site
logo_url: "https://dqyxw.github.io/about/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

paginate: 4

author: 大祁

gems: [jekyll-paginate]

introduction: 悲观者常常正确，乐观者才有可能成功。

tags: [杂记,other]